# Ensure redis-cli -> `CONFIG SET notify-keyspace-events K$` (KEA also works)
# notify-keyspace-events = "KEA" in /etc/redis/redis.conf

WALLET_PREFIX: "juno"
TOKEN_DENOM: "ujunox"
TOKEN_DENOM_NAME: "Juno"

ADMIN_PERM: "crafteconomy.admin"

# http://api.crafteconomy.io/v1/dao/escrow_account_info
REST_API_WALLET_ADDRESS: juno1efd63aw40lxf3n4mhf7dzhjkr453axurv2zdzk
# DAO Mutlisig account
# Wallet #2 in test_node.sh
DAO_TAX_WALLET_ADDRESS: juno1hj5fveer5cjtn4wd6wstzugjfdxzl0xps73ftl

# API_MAKE_PAYMENT_ENDPOINT: http://api.crafteconomy.io/v1/dao/make_payment
INTERNAL_API: "http://localhost:4000"
API_MAKE_PAYMENT_ENDPOINT: http://localhost:4000/v1/dao/make_payment
REDIS_KEY_EXPIRE_TIME: 0
TX_QUERY_ENDPOINT: https://api.juno.strange.love/cosmos/tx/v1beta1/txs/{TENDERMINT_HASH}
TAX_RATE: 0.05
DEV_MODE: false
DEBUGGING_MSGS: true
API_ENDPOINT: https://api.juno.strange.love/
SIGNING_WEBAPP_LINK: http://15.204.162.18:8081/
DAO_ESCROW_ENDPOINT_SECRET: 'some.secret.here'
MongoDB:
  # uri: mongodb://user:PASSWORD@IP:27017/?authSource=admin
  uri: mongodb://localhost:27017
  database: crafteconomy
Redis:
  # uri: redis://:password@IP:6379
  uri: redis://localhost:6379

