name: craft-integration
version: "${project.version}"
author: Reecepbcups
main: com.crafteconomy.blockchain.CraftBlockchainPlugin
description: Blockchain integration for Cosmos by Reecepbcups
website: https://crafteconomy.io/
api-version: 1.18
api: "1.18"
database: true
commands:
  wallet:
    description: Cosmos wallet integration command
    usage: /<command>
    aliases: [craftwallet, cwallet]
  escrow:
    description: crafteconomy escrow account 
    usage: /<command>
    aliases: [craftescrow, esc]    